plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.seleniumhq.selenium:selenium-java:4.20.0'
    testImplementation 'io.github.bonigarcia:webdrivermanager:5.8.0'
    testImplementation 'org.testng:testng:7.10.2'
    testImplementation 'org.slf4j:slf4j-simple:2.0.13'
}

test {
    useTestNG()

    systemProperty 'file.encoding', 'UTF-8'

    testLogging {
        events "passed", "skipped", "failed"
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}